apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../example

patches:
- patch: |
    - op: replace
      path: /helm/values
      value:
        image:
          ref: local-skaffold/gardener-extension-registry-cache:v0.0.0
        imageVectorOverwrite:
          images:
          - name: spegel-peers
            ref: registry.local.gardener.cloud:5001/local-skaffold_gardener-extension-registry-cache-spegel-peers:v0.20.0-8-g8bf9a5b1-dirty@sha256:873f5b5876dc45d61bfd2b1da00f73d4b8086e9b936f8182423007775f9e394f
  target:
    group: core.gardener.cloud
    kind: ControllerDeployment
    name: extension-registry-cache