apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../example

patches:
- patch: |
    - op: replace
      path: /helm/values
      value:
        image:
          ref: local-skaffold/gardener-extension-registry-cache:v0.0.0
        imageVectorOverwrite:
          images:
          - name: spegel-peers
            ref: registry.local.gardener.cloud:5001/local-skaffold_gardener-extension-registry-cache-spegel-peers:v0.20.0-10-ga2a51439-dirty@sha256:99faa1e3bd947a7b16ca64a7695a14eec4fdea46ac4076356c02f7c1bbc1b0b0
  target:
    group: core.gardener.cloud
    kind: ControllerDeployment
    name: extension-registry-cache