apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../example

patches:
- patch: |
    - op: replace
      path: /helm/values
      value:
        image:
          ref: local-skaffold/gardener-extension-registry-cache:v0.0.0
        imageVectorOverwrite:
          images:
          - name: spegel-peers
            ref: registry.local.gardener.cloud:5001/local-skaffold_gardener-extension-registry-cache-spegel-peers:v0.20.0-9-g826d45d9-dirty@sha256:4805ecd91e7355e426be9ed58f13e45f1dd16b2a664083c2adcd3ddb2b5e9fe8
  target:
    group: core.gardener.cloud
    kind: ControllerDeployment
    name: extension-registry-cache