{
 "title": "Spegel Registry",
 "description": "Spegel Registry",
 "tags": [
  "shoot",
  "cache"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "Aggregation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total bytes",
   "type": "stat",
   "description": "Bytes streams to containerD clients",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_response_size_bytes_sum[5m]))/2"
    }
   ]
  },
  {
   "title": "Hit rate",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(spegel_mirror_requests_total{cache=\"hit\"}[5m])) / sum(increase(spegel_mirror_requests_total[5m]))",
     "legendFormat": "hit rate"
    }
   ]
  },
  {
   "title": "Miss rate",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(spegel_mirror_requests_total{cache=\"miss\"}[5m])) / sum(increase(spegel_mirror_requests_total[5m]))",
     "legendFormat": "miss rate"
    }
   ]
  },
  { "title": "Spegel", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Cache Hits and Misses Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (registry) (rate(spegel_mirror_requests_total{cache=\"hit\"}[$__rate_interval]))",
     "legendFormat": "hit {{ registry }}"
    },
    {
     "expr": "sum by (registry) (rate(spegel_mirror_requests_total{cache=\"miss\"}[$__rate_interval]))",
     "legendFormat": "miss {{ registry }}"
    }
   ]
  },
  {
   "title": "Router latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(spegel_resolve_duration_seconds_bucket[5m])) by (le)) * 1000",
     "legendFormat": "latency"
    }
   ]
  },
  {
   "title": "Advertised content digests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (registry) (spegel_advertised_content_digests)",
     "legendFormat": "{{ registry }}"
    }
   ]
  },
  {
   "title": "Advertised image tags",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (registry) (spegel_advertised_image_tags)",
     "legendFormat": "{{ registry }}"
    }
   ]
  }
 ]
}