//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// SPDX-FileCopyrightText: SAP SE or an SAP affiliate company and Gardener contributors
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpegelConfig) DeepCopyInto(out *SpegelConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	if in.RegistryPort != nil {
		in, out := &in.RegistryPort, &out.RegistryPort
		*out = new(int32)
		**out = **in
	}
	if in.RouterPort != nil {
		in, out := &in.RouterPort, &out.RouterPort
		*out = new(int32)
		**out = **in
	}
	if in.MetricsPort != nil {
		in, out := &in.MetricsPort, &out.MetricsPort
		*out = new(int32)
		**out = **in
	}
	if in.ResolveTags != nil {
		in, out := &in.ResolveTags, &out.ResolveTags
		*out = new(bool)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpegelConfig.
func (in *SpegelConfig) DeepCopy() *SpegelConfig {
	if in == nil {
		return nil
	}
	out := new(SpegelConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SpegelConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpegelStatus) DeepCopyInto(out *SpegelStatus) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpegelStatus.
func (in *SpegelStatus) DeepCopy() *SpegelStatus {
	if in == nil {
		return nil
	}
	out := new(SpegelStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SpegelStatus) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
